net: wireless: scsc: Address unused variable error
../../../../../../kernel/samsung/gta4xl/drivers/net/wireless/scsc/mgt.c:7736:6: error: unused variable 'ret' [-Werror,-Wunused-variable]
        int ret = 0;
            ^
1 error generated.

Change-Id: I6a7dade4858ab7f61c96e4f43f824702297b3b2b